### ISSUE TITLE
Problem: Missing DOI

### ISSUE THREAD

**Issue by julianpistorius** [felixludos/omni-fig#2]
From https://github.com/openjournals/joss-reviews/issues/5350#issuecomment-1500681422

```
MISSING DOIs

- 10.1109/access.2022.3158675 may be a valid DOI for title: Reproducibility in Computing Research: An Empirical Study
```

**Comment by julianpistorius** [comment]
@felixludos this is apparently a prerequisite for me signing off on my review. See here: https://github.com/openjournals/joss-reviews/issues/5350#issuecomment-1532158241

**Comment by felixludos** [comment]
The missing DOI should be fixed now.
Sorry for the delay!
